apiVersion: apps/v1
kind: Deployment
metadata:
  name: livestream-service
  labels:
    app: livestream-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: livestream-service
  template:
    metadata:
      labels:
        app: livestream-service
    spec:
      automountServiceAccountToken: false
      containers:
      - name: livestream-service
        image: us-central1-docker.pkg.dev/livedj-project/livedj-repo/livestream-service:main
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        env:
        - name: MongoDB-ConnectionString
          valueFrom:
            secretKeyRef:
              name: livestream-secrets
              key: DATABASE_CONNECTION_STRING
        - name: Database-Name
          valueFrom:
            secretKeyRef:
              name: livestream-secrets
              key: DATABASE_NAME
        - name: Collection-Name
          valueFrom:
            secretKeyRef:
              name: livestream-secrets
              key: COLLECTION_NAME
